apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    app: frontend
    env: dev
spec:
  containers:
    - name: frontend-container
      image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: backend-pod
  labels:
    app: backend
    env: dev
spec:
  containers:
    - name: backend-container
      image: python:3.6-alpine
      command:
        [
          "sh",
          "-c",
          "echo container_2 > index.html && python -m http.server 8001",
        ]
