apiVersion: v1
kind: Pod
metadata:
  name: two-containers-pod
spec:
  containers:
    - name: container1
      image: python:3.6-alpine
      command:
        [
          "sh",
          "-c",
          "echo container_1 > index.html && python -m http.server 8000",
        ]
    - name: container2
      image: python:3.6-alpine
      command:
        [
          "sh",
          "-c",
          "echo container_2 > index.html && python -m http.server 8001",
        ]
