apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-test
  labels:
    app: app-web
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app-web
  template:
    metadata:
      labels:
        app: app-web
    spec:
      containers:
        - name: app-web
          image: nginx:alpine
---
apiVersion: v1
kind: Service
metadata:
  name: service-test
  labels:
    app: app-web
spec:
  type: ClusterIP
  selector:
    app: app-web
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
